# Generated by Django 5.0 on 2023-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.FloatField()),
                ('tenure', models.FloatField()),
                ('interest', models.FloatField()),
                ('loan_type', models.CharField(choices=[('1', 'Plan 1'), ('2', 'Plan2')], max_length=2)),
            ],
        ),
    ]
