# Generated by Django 5.0 on 2023-12-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_calculator', '0002_loan_monthly_repayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('1', 'Plan 1 Compound intrest'), ('2', 'Plan2 Simple intrest')], max_length=2),
        ),
    ]
